/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as OrderNowRouteImport } from './routes/order-now'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as AdminDailySalesRouteImport } from './routes/admin/daily-sales'
import { Route as AdminStorageRouteImport } from './routes/admin/storage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderNowRoute = OrderNowRouteImport.update({
  id: '/order-now',
  path: '/order-now',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDailySalesRoute = AdminDailySalesRouteImport.update({
  id: '/daily-sales',
  path: '/daily-sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStorageRoute = AdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/order-now': typeof OrderNowRoute
  '/track-order': typeof TrackOrderRoute
  '/admin/daily-sales': typeof AdminDailySalesRoute
  '/admin/storage': typeof AdminStorageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/order-now': typeof OrderNowRoute
  '/track-order': typeof TrackOrderRoute
  '/admin/daily-sales': typeof AdminDailySalesRoute
  '/admin/storage': typeof AdminStorageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/order-now': typeof OrderNowRoute
  '/track-order': typeof TrackOrderRoute
  '/admin/daily-sales': typeof AdminDailySalesRoute
  '/admin/storage': typeof AdminStorageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/menu'
    | '/order-confirmed'
    | '/order-now'
    | '/track-order'
    | '/admin/daily-sales'
    | '/admin/storage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/menu'
    | '/order-confirmed'
    | '/order-now'
    | '/track-order'
    | '/admin/daily-sales'
    | '/admin/storage'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/menu'
    | '/order-confirmed'
    | '/order-now'
    | '/track-order'
    | '/admin/daily-sales'
    | '/admin/storage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  MenuRoute: typeof MenuRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  OrderNowRoute: typeof OrderNowRoute
  TrackOrderRoute: typeof TrackOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-now': {
      id: '/order-now'
      path: '/order-now'
      fullPath: '/order-now'
      preLoaderRoute: typeof OrderNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/daily-sales': {
      id: '/admin/daily-sales'
      path: '/daily-sales'
      fullPath: '/admin/daily-sales'
      preLoaderRoute: typeof AdminDailySalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/storage': {
      id: '/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AdminStorageRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDailySalesRoute: typeof AdminDailySalesRoute
  AdminStorageRoute: typeof AdminStorageRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDailySalesRoute: AdminDailySalesRoute,
  AdminStorageRoute: AdminStorageRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  MenuRoute: MenuRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  OrderNowRoute: OrderNowRoute,
  TrackOrderRoute: TrackOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
